### ISSUE TITLE
call.getFileName is not a function

### ISSUE THREAD

**Issue by kaosine** [pulsar-edit/atom-ide-javascript#1]
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Fails to load:

### Versions

**Atom**: 1.63.2022092716 x64
**Electron**: 12.2.3
**OS**: linux 5.19.12-300.fc37.x86_64
**Thrown From**: [atom-ide-javascript](https://github.com/atom-ide-community/atom-ide-javascript) package 1.5.0

### Stack Trace

Failed to load the atom-ide-javascript package

```
At call.getFileName is not a function

TypeError: call.getFileName is not a function
    at getErrMessage (assert.js:279:25)
    at innerOk (assert.js:370:17)
    at ok (assert.js:390:3)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:45:21)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-commons-ui/Dropdown.js:305:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:16:17)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachUiComponent.js:519:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:14:62)
    at /packages/atom-ide-javascript/node_modules/@atom-ide-community/nuclide-debugger-common/AutoGenLaunchAttachProvider.js:109:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
```

### Commands

```
     -2:42.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:37.1.0 editor:consolidate-selections (input.hidden-input)
     -2:37.1.0 core:cancel (input.hidden-input)
     -1:50.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
after-dark-syntax 0.1.0 
all-green-ui 0.1.0 
atom-folding 0.0.9 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.3 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
busy-signal 2.0.1 
folding-markdown 0.1.4 
hard-wrap 1.7.1 
ide-java 0.9.1 
intentions 2.1.1 
linter 3.4.0 
linter-languagetool 0.11.0 
linter-ui-default 3.4.1 
monokai-solarized-dark 0.1.1 
prettier-atom-with-tabs 0.18.4 
ptx-solarized-dark-syntax 0.1.0 
```

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 37 Beta

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Install
2. Wait for it to try and load after this
3. Error automatically comes up

**Comment by confused-Techie** [comment]
While this doesn't lead to the solution here, if it helps anyone looking later on.

One of the packages referenced here is the `atom-community/atom-ide-base` Or as shown in the package [`@atom-ide-community/nuclide-commons-ui`](https://www.npmjs.com/package/@atom-ide-community/nuclide-commons-ui/v/0.8.2), specifically `atom-ide-javascript` is using Version 0.8.2, and has references in this error to `Dropdown.js` which that specific version of the file can be viewed in on [their repo](https://github.com/atom-community/atom-ide-base/blob/52ae3fcb2d0aed7ca12e09b9b4ab66859cdbe04e/nuclide/nuclide-commons-ui/Dropdown.js).

Although Line 45:

```javascript
36: export type MenuItem = {
37:   type?: void,
38:   value: any,
39:   label: string,
40:   selectedLabel?: string,
41:   submenu?: void,
42:   icon?: IconName,
43:   iconset?: string,
44:   disabled?: boolean,
45:   hidden?: boolean,
46: };
```

Then Line 305 is a blank line between these two segments:

```javascript
const ButtonComponent = buttonComponent || Button;
const className = classnames('nuclide-ui-dropdown', this.props.className, {
   'nuclide-ui-dropdown-flat': isFlat === true,
});
```

and 

```javascript
const label =
      children == null ? (
        <span className="sr-only">Open Dropdown</span>
      ) : (
        <span className="nuclide-dropdown-label-text-wrapper">{children}</span>
      );
```

So this might not show us the error, and seems really strange being honest. But hopefully can be helpful in finding whats causing this.
